# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 20:02
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=geoposition.fields.GeopositionField(default=0, max_length=42),
        ),
    ]
