# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 20:16
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170812_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
