# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170812_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Event'),
        ),
    ]
