# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 22:34
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170815_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
