# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170907_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
