# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170907_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
